# https://circleci.com/blog/streamlined-web-application-testing-with-the-cypress-circleci-orb/

# https://docs.cypress.io/guides/continuous-integration/introduction#CircleCI
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.27.0
# workflows:
#   build: 
#     jobs:
#       - cypress/install:
#           build: yarn run build # run a custom app build step
#           yarn: true
#       - cypress/run:
#           requires:
#             - cypress/install
#           parallel: true # split all specs across machines
#           parallelism: 4 # use 4 CircleCI machines to finish quickly
#           yarn: true
#           group: 'all tests' # name this group "all tests" on the dashboard
#           start: yarn start # start server before running tests



version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:12
        environment:
          ## this enables colors in the output
          TERM: xterm
    # working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

  startDev:
    docker:
      - image: cypress/base:12
        environment:
          ## this enables colors in the output
          TERM: xterm
    # working_directory: ~/app
    steps:
      - run: yarn start

  test:
    docker:
      - image: cypress/base:12
        environment:
          ## this enables colors in the output
          TERM: xterm
    # working_directory: ~/app
    steps:
      - run: $(yarn bin)/cypress run


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - startDev:
          requires:
              - build
      - test:
          requires:
            # - startDev
            - build


# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       # install dependencies first (on 1 machine)
#       - cypress/install

#       # now run tests
#       - cypress/run:
#           # give this job a custom name for clarity
#           name: 'end-to-end tests'
#           requires:
#             # use previously installed dependencies
#             # to avoid installing them on each machine running tests
#             - cypress/install
#           executor: cypress/base-14   
#           # yarn: true         
#           parallel: true # run tests in parallel
#           parallelism: 3 # use 3 CircleCI machines
#           group: 3 machines # name this group "3 machines"


# version: 2.1

# jobs:
#   build:
#     working_directory: ~/tmp
#     docker:
#       - image: 'cypress/base:12'
#         environment:
#           TERM: xterm
#     steps:
#       - checkout
#       - run: pwd
#       - run: ls
#       - run: yarn ci
#   test:
#     working_directory: ~/tmp
#     docker:
#       - image: 'cypress/base:12'
#         environment:
#           TERM: xterm
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: ls -la cypress
#       - run: ls -la cypress/integration
#       - run:
#           name: Running cypress tests
#           command: $(yarn bin)/cypress run

# workflows:
#   version: 2.1
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
