version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:12
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/portalo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run: 
          name: Compile and start development server
          command: yarn startOnPort3000Linux
          background: true
      - run: 
          name: Wait for development server to start
          command: 'yarn wait-on http://localhost:3000'
      - run: 
          name: Run routing tests with react-testing-library via yarn test
          command: 'yarn test src/tests/react-testing-library/routing.test.tsx'
      - run: 
          name: Run e2e tests with Cypruss via cypress run
          command: $(yarn bin)/cypress run

  # test:
  #   docker:
  #     - image: cypress/base:12
  #       environment:
  #         ## this enables colors in the output
  #         TERM: xterm
  #   working_directory: ~/portalo
  #   steps:
  #     - run: pwd
  #     - run: ls -l
  #     - run: $(yarn bin)/cypress run


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      # - startDev:
      #     requires:
      #         - build
      # - test:
      #     requires:
      #       # - startDev
      #       - build

# version: 2.1

# jobs:
#   build:
#     working_directory: ~/tmp
#     docker:
#       - image: 'cypress/base:12'
#         environment:
#           TERM: xterm
#     steps:
#       - checkout
#       - run: pwd
#       - run: ls
#       - run: yarn ci
#   test:
#     working_directory: ~/tmp
#     docker:
#       - image: 'cypress/base:12'
#         environment:
#           TERM: xterm
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: ls -la cypress
#       - run: ls -la cypress/integration
#       - run:
#           name: Running cypress tests
#           command: $(yarn bin)/cypress run

# workflows:
#   version: 2.1
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
