version: 2.1
jobs:
  run_tests:
    docker:
      - image: cypress/base:12
        environment:
          # this enables colors in the output
          TERM: xterm
    working_directory: ~/portalo
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: yarn install --frozen-lockfile
      - run: 
          name: Compile and start development server on port 3000
          command: yarn startOnPort3000Linux
          background: true
      - run: 
          name: Wait for development server to start
          command: 'yarn wait-on http://localhost:3000'
      - run: 
          name: Run routing tests with react-testing-library via yarn test
          command: 'yarn test ~/portalo/src/tests/react-testing-library/routing.test.tsx'
      - run: 
          name: Run e2e tests with Cypruss via cypress run
          command: $(yarn bin)/cypress run

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - run_tests
      #     requires:
      #         - build

# - restore_cache:
#     keys:
#       # when lock file changes, use increasingly general patterns to restore cache
#       - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
#       - yarn-packages-v1-{{ .Branch }}-
#       - yarn-packages-v1-
# - save_cache:
#     paths:
#       - ~/.cache/yarn
#     key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}