version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys: 
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the lastest cache if no exact match is found
          - v1-dependencies

      - run: 
          name: Install all packages
          command: yarn install

      - save_cache: 
        paths:
          - node_modules
        keys: v1-dependencies-{{ checksum "package.json" }}

        # tests 
      - run: 
          name: Run all tests
          command: |
            yarn cypress run
            yarn test -- src/tests/react-testing-library/routing.test.tsx

      #- run: yarn build
    #working_directory: ~/repo
