version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
      # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - run: 
          name: Install all packages
          command: yarn install
      - run: 
          name: Start local dev env
          command: |
            yarn startPort3000
      - run: 
          name: Run all tests
          command: |
            yarn cypress run
            yarn test -- src/tests/react-testing-library/routing.test.tsx
