# https://circleci.com/blog/streamlined-web-application-testing-with-the-cypress-circleci-orb/

# https://docs.cypress.io/guides/continuous-integration/introduction#CircleCI
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.27.0
# workflows:
#   build: 
#     jobs:
#       - cypress/install:
#           build: yarn run build # run a custom app build step
#           yarn: true
#       - cypress/run:
#           requires:
#             - cypress/install
#           parallel: true # split all specs across machines
#           parallelism: 4 # use 4 CircleCI machines to finish quickly
#           yarn: true
#           group: 'all tests' # name this group "all tests" on the dashboard
#           start: yarn start # start server before running tests

version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  react: thefrontside/react@0.1.0
workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          no-workspace: true


# version: 2.1
# # Define the jobs we want to run for this project
# jobs:
#   build:
#       # pre-built images: https://circleci.com/docs/2.0/circleci-images/ 
#     docker:
#       - image: circleci/node:12.10
#     steps:
#       - checkout
#       - run: 
#           name: Install all packages
#           command: yarn install
#       - run: 
#           name: Start local dev env
#           command: |
#             yarn startPort3000
#       - run: 
#           name: Run all tests
#           command: |
#             yarn cypress run
#             yarn test -- src/tests/react-testing-library/routing.test.tsx
