service: portalo2

plugins:
  - serverless-iam-roles-per-function

# deplyes each function individually
package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  login:
    handler: login.login
    memorySize: 128
    description: Function that log user.
    events:
    - http: 
        path: /login
        method: get
        # cors: true # preflight requests
    iamRoleStatementsName: employeesDynamoDescribeScanPutGetUpdateDelete 
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DescribeTable
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:UpdateTable
      Resource: arn:aws:dynamodb:eu-central-1:336526891729:table/Employees
  register:
    handler: register.register
    memorySize: 128
    description: Function that register user.
    events:
    - http: 
        path: /register
        method: post
        # cors: true

# resources:
#   Resources:
#     MyDynamoDBEmployeesTable:
#       Type: AWS::DynamoDB::Table
#       Properties: 
#         TableName: Employees
#         AttributeDefinitions: 
#           - AttributeName: username
#             AttributeType: S
#         KeySchema: 
#           - AttributeName: username
#             KeyType: HASH
#         TimeToLiveSpecification: 
#           AttributeName: ExpirationTime
#           Enabled: true
#         ProvisionedThroughput: 
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#     MyIamPolicy:
#       Type: AWS::IAM::ManagedPolicy
#       Properties:
#         Description: Policy for using a table Employees in DynamoDB
#         # PolicyName: employeesDynamoDescribeScanPutGetUpdateDelete
#         PolicyDocument:
#           Version: '2012-10-17'
#           Statement:
#             - 
#               Effect: Allow
#               Action:
#                 - dynamodb:PutItem
#                 - dynamodb:DescribeTable
#                 - dynamodb:DeleteItem
#                 - dynamodb:GetItem
#                 - dynamodb:Query
#                 - dynamodb:UpdateItem
#                 - dynamodb:UpdateTable
#               Resource: arn:aws:dynamodb:eu-central-1:336526891729:table/Employees
